version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - aws s3 rm s3://hiker-meetup-frontend --recursive

  build:
    commands:
      - npm install
      - npm install aws-amplify 
      - npm run build
    
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: no