const FORM_INITIAL_STATE = "FORM_INITIAL_STATE";
const FORM1_CHECK_READY = "FORM1_CHECK_READY";
const FORM_SUBMIT_CHECK_READY = "FORM_SUBMIT_CHECK_READY";

const READY_TO_SUBMIT = "READY_TO_SUBMIT";
const SUBMIT_EVENT = "SUBMIT_EVENT";
const SUBMISSION_SUCCESS = "SUBMISSION_SUCCESS";

export {
  FORM_INITIAL_STATE,
  FORM1_CHECK_READY,
  FORM_SUBMIT_CHECK_READY,
  READY_TO_SUBMIT,
  SUBMIT_EVENT,
  SUBMISSION_SUCCESS
};
