const ORF_MODULE = "ORF";
const MANAGER_BUTTON_GROUP = "MANAGER_BUTTON_GROUP";
const DRAFTER_BUTTON_GROUP = "DRAFTER_BUTTON_GROUP";
const VERIFIER_BUTTON_GROUP = "VERIFIER_BUTTON_GROUP";

const GENERAL_MODULE = "GENERAL";
const TROUBLESHOOTING_MODULE = "TROUBLESHOOTING";
const ORDER_PROCESSING_MODULE = "ORDER_PROCESSING";
const PARTS_MASTER_DATA_MODULE = "PARTS_MASTER_DATA";
const REPORTS_MODULE = "REPORTS";
const MISCELLANEOUS_MODULE = "MISCELLANEOUS";
const SYSTEM_MODULE = "SYSTEM";

export {
  GENERAL_MODULE,
  SYSTEM_MODULE,
  MISCELLANEOUS_MODULE,
  REPORTS_MODULE,
  PARTS_MASTER_DATA_MODULE,
  ORDER_PROCESSING_MODULE,
  TROUBLESHOOTING_MODULE,
  ORF_MODULE,
  MANAGER_BUTTON_GROUP,
  DRAFTER_BUTTON_GROUP,
  VERIFIER_BUTTON_GROUP
};
