import React, { Fragment } from "react";
import { withRouter } from "react-router-dom";
// nodejs classes
import PropTypes from "prop-types";
// @material-ui/core components
import { Typography } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
// material ui icons
import DashboardIcon from "@material-ui/icons/Dashboard";
// core components
import GridContainer from "../_rootComponent/Grid/GridContainer";
import GridItem from "../_rootComponent/Grid/GridItem";
import Table from "../_rootComponent/Table/Table";
// sub components
// style for this view
import formStyle from "../_rootAsset/jss/formStyle";
//others

const useFormStyle = makeStyles(formStyle);

const DepartmentTaskReadSingleView = () => {
  const classes = { ...useFormStyle() };
  const acronymHeader = [
    "S/N",
    "Acronym",
    "Definition",
    "Description",
    "Use By"
  ];
  const acronymData = [
    [
      "DIL",
      "Delivery Instruction List",
      "A document containing the instructions for packers (e.g. Items to be picked, delivery date, etc). Usually generated by SAP upon close tag.",
      "EHD"
    ],
    [
      "GRN",
      "Goods Received Notes",
      "https://accountantskills.com/what-is-goods-received-note-grn/",
      "FIN & Store"
    ],
    [
      "PMS",
      "To be available.",
      "Engingeering document issued by Japan as part of FZ2.",
      "FIN & Store"
    ],
    [
      "FZ2",
      "No Definition",
      "A package of Engineering (PMS) Documents. This issued from Japan via email and downloaded from Terra Portal.",
      "Engineering Departments"
    ]
  ];

  return (
    <div>
      <GridContainer className={classes.parentContainer}>
        <GridItem lg={12}>
          <Fragment>
            <GridContainer>
              <GridItem>
                <p className={classes.title}>
                  Welcome to Collabo Web. This is the new version of Data
                  Download Center (DDC).
                </p>
                <div className={classes.iconWrapper}>
                  <DashboardIcon fontSize="small" />
                </div>
              </GridItem>
            </GridContainer>
            <GridContainer>
              <GridItem lg={12}>
                <div className={classes.subTitleWrapper}>
                  <Typography className={classes.subTitle}>
                    Company-wide Glossary
                  </Typography>
                </div>
              </GridItem>
            </GridContainer>
            <GridContainer>
              <GridItem lg={12}>
                <Table
                  striped
                  tableHead={acronymHeader}
                  tableData={acronymData
                    .sort((a, b) => {
                      if (a[0] === b[0]) return 0;
                      return a[0] > b[0] ? 1 : -1;
                    })
                    .map((rowData, index) => {
                      return [index + 1, ...rowData];
                    })}
                />
              </GridItem>
            </GridContainer>
          </Fragment>
        </GridItem>
      </GridContainer>
    </div>
  );
};

DepartmentTaskReadSingleView.propTypes = {
  history: PropTypes.object,
  match: PropTypes.object,
  location: PropTypes.object,
  children: PropTypes.node
};

export default withRouter(DepartmentTaskReadSingleView);
